server.port: 7000

spring.datasource:
  driver-class-name: oracle.jdbc.driver.OracleDriver
  url: "jdbc:oracle:thin:@lbtest_tp?TNS_ADMIN=/Users/jmalbarran/Projects/ORA/ORA/PoC_LiquidBase/oracle-liquibase/keystore/wallet"
  username: admin
  password: 1UPPERCASE#1lowercase

spring.jpa:
  show-sql: true
  database: oracle

