server.port: 7000

spring.datasource:
  driver-class-name: oracle.jdbc.driver.OracleDriver
  # url: "jdbc:oracle:thin:@lbtest_tp?TNS_ADMIN=${TNS_ADMIN}"
  # username: "${DB_USER}"
  # password: "${DB_PASSWORD}"

spring.jpa:
  open-in-view: false
  show-sql: true
  database: oracle

